[Autologin]
User=live-user
Session=plasma
Relogin=false

[Users]
MinimumUid=1000

[Theme]
Current=zenos-sddm

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[X11]
ServerArguments=-nolisten tcp -dpi 96
