# ZEN-OS GameMode configuration
[general]
renice = 10

[gpu]
apply_gpu_optimisations = accept-responsibility
gpu_device = 0
nv_powermizer_mode = auto

[cpu]
park_cores = no
pin_cores = no

[supervisor]
supervisor = systemd

[custom]
start = /usr/local/bin/game-mode-start.sh
end = /usr/local/bin/game-mode-stop.sh
